name: Build app and run cypress tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./my-app
        run: npm install
      - name: Up app
        working-directory: ./my-app
        run: npm run dev &
      - name: Run tests
        working-directory: ./my-app
        run: npm run test:e2e:run
