name: Build app and run cypress tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        working-directory: ./my-app
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./my-app
        run: npm install

      - name: Run tests
        working-directory: ./my-app
        run: npm run test:e2e:run
